# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ilario Bonacina
email: ilario@kth.se
description: > # this means to ignore newlines until "baseurl:"
  I'm currently a Postdoctoral researcher at the KTH Royal Institute of Technology in Stockholm (Sweden).
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


email_private: ilariobonacina@gmail.com
work_email: ilario@kth.se
work_address: > #
  KTH Royal Institute of Technology <br>
  School of Computer Science and Communication <br>
  SE-100 44 Stockholm <br>
  SWEDEN
work_visiting_address: Osquars backe 2, 5th floor, office 4519
twitter_username: no
github_username:  IlarioBonacina
facebook_username: i.goodchina
skype_username: no

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock

scholar:
  style: _plugins/apa.csl
  locale: en

  sort_by: year,month
  order: descending

  repository: pdf

  bibliography_list_attributes:
    reversed: "reversed"

  group_by: none
  group_order: descending

  source: ./_bibliography
  bibliography: references.bib
  bibliography_template: bib
  bibliography_list_tag: none
  bibliography_item_tag: none

  use_raw_bibtex_entry: true
  bibtex_filters:
    - superscript
    - latex
    - markdown
